import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './styles.css';

// Registers the PWA service worker (generated by vite-plugin-pwa).
// In dev this is a no-op; in a production build it enables installability.
import { registerSW } from 'virtual:pwa-register';
registerSW({ immediate: true });

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
